CPP=g++
CPPFLAGS=-Wall


fibonacci-sc:
	$(CPP) $(CPPFLAGS) fibonacci-sc.cpp fibonacci-sc.h main.cpp -o fibonacci-sc

fibonacci-cc:
	$(CPP) $(CPPFLAGS) fibonacci-cc.cpp fibonacci-cc.h main.cpp -o fibonacci-cc


clean: 
	rm -vf fibonacci-sc *.o